name: Check coding style

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
